server:
  port: 80
logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://dbpostgresql:5432/postgres?currentSchema=catalog
    username: postgres
    password: postgres
    pool-size: 30
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  flyway:
    url: jdbc:postgresql://dbpostgresql:5432/postgres
    schemas: catalog
    user: postgres
    password: postgres

springfox:
  documentation:
    service-version: local

urls:
  imports: /imports
  nodes: /nodes
  delete: /delete
